#!/bin/bash
cpuusage=$(echo | cat cpuusage.txt)
varzero=$(echo | cat pid.txt)
cpulimit -p $varzero -l $cpuusage &
echo "$varzero"
var1=$((varzero+1))
sleep .5
cpulimit -p $var1 -l $cpuusage &
echo "$var1"
var2=$((var1+1))
sleep .5
cpulimit -p $var2 -l $cpuusage &
echo "$var2"
var3=$((var2+1))
sleep .5
cpulimit -p $var3 -l $cpuusage &
echo "$var3"
var4=$((var3+1))
sleep .5
cpulimit -p $var4 -l $cpuusage &
echo "$var4"
var5=$((var4+1))
sleep .5
cpulimit -p $var5 -l $cpuusage &
echo "$var5"
var6=$((var5+1))
sleep .5
cpulimit -p $var6 -l $cpuusage &
echo "$var6"
var7=$((var6+1))
sleep .5
cpulimit -p $var7 -l $cpuusage &
echo "$var7"
var8=$((var7+1))
sleep .5
cpulimit -p $var8 -l $cpuusage 
echo "$var8"
